// package gamingchair;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class GamingChairService {
	
	private Connection connection;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private String createTableGamingChair = "CREATE TABLE GamingChair(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(20) UNIQUE, vendor varchar(20), prize decimal(4,2))";

	
	private PreparedStatement addGamingChair;
	private PreparedStatement deleteAllGamingChairs;
	private PreparedStatement getAllGamingChairs;

	private Statement statement;
	//connection = DriverManager.getConnection(url);
	//4 atrybuty w encji nazwa firma cena komfort
	public GamingChairService() throws SQLException {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("GamingChair".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableGamingChair);

			addGamingChair = connection.prepareStatement("INSERT INTO GamingChair (name, vendor, prize) VALUES (?, ?, ?)");
			deleteAllGamingChairs = connection.prepareStatement("DELETE FROM GamingChair");
			getAllGamingChairs = connection.prepareStatement("SELECT id, name, vendor, prize FROM GamingChair");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	public static void main(String[] args) throws SQLException {
		System.out.println("No elo");
		//connection.prepareStatement("SELECT id, name, yob FROM Person");
		// TODO Auto-generated method stub
	/*
		public GamingChairService() throws SQLException {
		connection = DriverManager.getConnection(URL);
		sta
	}*/
	}

}


/*
package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbcdemo.domain.Person;

public class PersonManagerJDBC implements PersonManager {

	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTablePerson = "CREATE TABLE Person(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(20) UNIQUE, yob integer)";

	private PreparedStatement addPersonStmt;
	private PreparedStatement deleteAllPersonsStmt;
	private PreparedStatement getAllPersonsStmt;

	private Statement statement;

	public PersonManagerJDBC() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTablePerson);

			addPersonStmt = connection.prepareStatement("INSERT INTO Person (name, yob) VALUES (?, ?)");
			deleteAllPersonsStmt = connection.prepareStatement("DELETE FROM Person");
			getAllPersonsStmt = connection.prepareStatement("SELECT id, name, yob FROM Person");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

	void clearPersons() {
		try {
			deleteAllPersonsStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public int addPerson(Person person) {
		int count = 0;
		try {
			addPersonStmt.setString(1, person.getName());
			addPersonStmt.setInt(2, person.getYob());

			count = addPersonStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public List<Person> getAllPersons() {
		List<Person> persons = new ArrayList<Person>();

		try {
			ResultSet rs = getAllPersonsStmt.executeQuery();

			while (rs.next()) {
				Person p = new Person();
				p.setId(rs.getInt("id"));
				p.setName(rs.getString("name"));
				p.setYob(rs.getInt("yob"));
				persons.add(p);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return persons;
	}

	@Override
	public void addAllPersons(List<Person> persons) {

		try {
			connection.setAutoCommit(false);
			for (Person person : persons) {
				addPersonStmt.setString(1, person.getName());
				addPersonStmt.setInt(2, person.getYob());
				addPersonStmt.executeUpdate();
			}
			connection.commit();
			
		} catch (SQLException exception) {
			
			try {
				connection.rollback();
			} catch (SQLException e) {
				e.printStackTrace();
				//!!!! ALARM
			}
		}

	}

}
*/